### ISSUE TITLE
Webpacker 6 doesn't support custom installers anymore.

### ISSUE THREAD

**Issue by alexanderadam** [lewagon/rails-templates#147]
I just ran into the following error and it seems that

> [Webpacker 6 doesn't support custom installers anymore.](https://github.com/rails/webpacker/issues/3052#issuecomment-861881027)

```
[…]
success Saved 2 new dependencies.
info Direct dependencies
├─ @popperjs/core@2.11.5
└─ bootstrap@5.1.3
info All dependencies
├─ @popperjs/core@2.11.5
└─ bootstrap@5.1.3
Done in 0.68s.
         run  rails webpacker:install:stimulus from "."
rails aborted!
Don't know how to build task 'webpacker:install:stimulus' (See the list of available tasks with `rails --tasks`)

(See full trace by running task with --trace)
```

**Comment by dmilon** [comment]
Hi @alexanderadam :wave: Thank you for your report :pray: 

Our `master` branch Rails templates have been made for Rails 6 for which Stimulus is not installed by default. Since Rails 7, Stimulus comes preinstalled with `rails new` and so the `webpacker:install:stimulus` task doesn't exist anymore for this version of Rails, leading to this error.

Please use a Rails 6 gem version if you use our `master` branch Rails templates. If you want to use Rails 7, use the `rails-7` [branch templates](https://github.com/lewagon/rails-templates/tree/rails-7) :pray: 

I've just added [a warning](https://github.com/lewagon/rails-templates/commit/36e676a8b5b2c183e15b5b26e46f17ae87926b7d) to remove any doubt.
