### ISSUE TITLE
why is assets.debug turned off in development?

### ISSUE THREAD

**Issue by adipasquale** [lewagon/rails-templates#91]
I don't understand why the `config.assets.debug` is forced to false in the development environment. 

https://github.com/lewagon/rails-templates/blob/dce210391c7716b1f0fa6c029603eb03e9b42df6/minimal.rb#L63

My understanding of this config is that it enables on-the-fly assets compiling. However, I'm also  weirded out that disabling it doesn't seem to _always_ disable on-the-fly assets compiling. @grmnlrt told me that it might have to do with the fact that the lewagon template has a single scss file, but I still don't get it, would someone explain it to me?

A student had a problem today where he had precompiled assets locally once, and the on-the-fly compiling would never pick up again before we clobbered local assets.

**Comment by ssaunier** [comment]
Hello @adipasquale,

I think that the debug set to false was so that the HTML source does not get scattered with tens of `<link>` and `<script>` files from Sprockets, slowing down a lot page loads in development.

As of the bug regarding with precompiled assets, it's common when a student runs `rails assets:precompile` locally. In that case Rails will take the CSS from `public/assets` folder without considering the source. The solution is to clobber the assets and explain the students why the precompile command is not to be run locally and is automatically run on Heroku at each `git push`.

**Comment by adipasquale** [comment]
thanks for the quick answer @ssaunier !

Do you have any idea why Rails still perform on-the-fly assets compiling even though we explicitly disable it with this setting though?

**Comment by ssaunier** [comment]
Sure! Does [this](https://stackoverflow.com/a/20859448) answer your follow-up question? (not sure I got it right)

**Comment by adipasquale** [comment]
oh right, perfect, got it :) thanks
